### ISSUE TITLE
ERROR_WRONG_CUSTOM_INFO -> TD-2130N

### ISSUE THREAD

**Issue by tagercito** [gordol/cordova-brother-label-printer#16]
I'm trying to implement a TD-2130N but I keep getting this error:

ERROR_WRONG_CUSTOM_INFO

Documentation says : Wrong information in custom paper setting file

I've tried adding the .bin file in the “customPaperFileSet” path in the sdcard (and upload it to the phone):

>  myPrinterInfo.customPaper   = "/sdcard/customPaperFileSet/pdt3635.bin";

but same message.

Documentation also says that it should work this way:
 

> myPrinter.setPrinterInfo(myPrinterInfo);
> LabelInfo label = myPrinter.getLabelInfo();

but in that way I wouldn't be specifying the path to the settings.

Any thoughts? I'm totally lost.

**Comment by tagercito** [comment]
I have also tried getting the path to the custom paper from the environment with the correct path.

**Comment by tagercito** [comment]
Fixed it.

Had to export the .bin file specifically for 1 paper type in order for the app to get it.

TD_2130N works with the plugin.

You just have to set customPaper and add a .bin file in a folder called /customPaperFileSet/ in the root of the sdcard.

**Comment by gordol** [comment]
cool!

did you test the dev or master version?
