### ISSUE TITLE
Change findNetworkPrinters response format

### ISSUE THREAD

**Issue by aabanaag** [gordol/cordova-brother-label-printer#18]
Hi, would it be possible to change the format of the response from findNetworkPrinters?

currently I'm seeing `[{nodeName=printer-1,ipAddress=123.55.12.1}]` is it possible to convert it to proper format?

**Comment by gordol** [comment]
what do you mean by "proper format"?

**Comment by aabanaag** [comment]
I mean proper array format? `[{nodeName: 'printer-1', ipAddress: '123.331.223.12'}]`

**Comment by aabanaag** [comment]
Also totally not related to the question/issue but how would I change the orientation when printing?

**Comment by gordol** [comment]
Can you provide more details? What platform are you testing on? What branch?

findNetworkPrinters on master should be returning a JSONArray, which Cordova handles the serialization of, not us...

See here: https://github.com/apache/cordova-android/blob/master/framework/src/org/apache/cordova/PluginResult.java#L46
