### ISSUE TITLE
Can't Install plugin for Ionic 2 and above

### ISSUE THREAD

**Issue by chetuBhadra93** [gordol/cordova-brother-label-printer#19]
Hello,
I am getting error while installing this plugin. I am using Ionic 2. Following are error which i am getting.
Error: Failed to fetch plugin. 
Probably this is either a connection problem, or plugin spec is incorrect.

Can any one help me to resolve this issue.

Thanks.

**Comment by gordol** [comment]
Hi, maybe it's not handling the redirect?

Try this URL: https://github.com/gordol/cordova-brother-label-printer

**Comment by chetuBhadra93** [comment]
Hey,
Thanks for your response.

I am facing still same issue while adding plugin. 
![brotherserror](https://user-images.githubusercontent.com/21984573/33426747-e9463908-d5e8-11e7-87e8-3508be82bdf8.png)

Please give some solution because ionic native printer plugin not detecting brother's printer.

**Comment by gordol** [comment]
`cordova plugin add git+https://github.com/gordol/cordova-brother-label-printer.git`
