### ISSUE TITLE
Plugin Configuration XML States Camera is Required

### ISSUE THREAD

**Issue by eugenedw** [gordol/cordova-brother-label-printer#4]
First off, great plugin - saved me after hours of trying to figure out why every driver for our Brother label printer wasn't working.

We automate builds and plugin updates. Our build script is failing due to duplicate entries for camera use. I see in your plugin.xml you state that the camera is required:

`<uses-feature android:name="android.hardware.camera" android:required="true" />`

Is this truly necessary? If not, are you willing to remove the requirement?

Thanks!

**Comment by bnowacky** [comment]
@eugenedw , Have you tried it with the line commented out? If it runs, we can remove it. I don't believe it's needed.

**Comment by eugenedw** [comment]
Thanks for asking. Yes, we've proceeded with storing a slightly customized version of the plugin for future builds that excludes this camera requirement. We've automated the builds to pull from a local folder. Here's an excerpt the plugin.xml file that we have:

&lt;config-file target="AndroidManifest.xml" parent="/manifest"&gt;
            &lt;uses-permission android:name="android.permission.CAMERA" /&gt;
            &lt;uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/&gt;
            &lt;uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/&gt;
            &lt;uses-permission android:name="android.permission.INTERNET"/&gt;
            &lt;uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" /&gt;
            &lt;!-- &lt;uses-feature android:name="android.hardware.camera" android:required="true" /&gt; --&gt;
            &lt;!-- &lt;uses-feature android:name="android.hardware.camera.autofocus" android:required="true" /&gt; --&gt;
        &lt;/config-file&gt;

**Comment by gordol** [comment]
Hmm...

@eugenedw I see that your build still has the camera permission.... is that required?
