### ISSUE TITLE
PrinterStatus: ERROR_INTERNAL_ERROR

### ISSUE THREAD

**Issue by sllobera** [gordol/cordova-brother-label-printer#7]
HI 
trying to print an image using printViaSDK

find the printer ok ( QL-720nw) but get PrinterStatus: ERROR_INTERNAL_ERROR when trying to send to printer

using SDK demo app works ok.

tried everything, cant figure it out

**Comment by Ayiga** [comment]
Hello @sllobera.  I just figured this out.  This plugin doesn't request permission for `Manifest.permission.WRITE_EXTERNAL_STORAGE`.  This needs to be requested from the user when the app launches.  The Brother printer writes all print jobs to storage before printing them, so it doesn't have to hold them in memory.

Adding the following to `BrotherPrinter.java` fixed the issue for me.  I've been trying to figure this out for the past two days.

```java
   private boolean isPermitWriteStorage() {

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
            if (cordova.getActivity().checkSelfPermission(Manifest.permission.WRITE_EXTERNAL_STORAGE)
                    != PackageManager.PERMISSION_GRANTED) {
                return false;
            }
        }
        return true;
    }

    public void pluginInitialize() {
        super.pluginInitialize();
        if (!isPermitWriteStorage()) {
            cordova.requestPermission(this, PERMISSION_WRITE_EXTERNAL_STORAGE, Manifest.permission.WRITE_EXTERNAL_STORAGE);
        }
    }
```

**Comment by gordol** [comment]
@Ayiga can you please send a pull request with your fix? Should those permissions be set in the config xml?

**Comment by gordol** [comment]
Hmm, that is indeed in the XML already.

`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />`

Is this a new permissions method for newer android versions?

**Comment by Ayiga** [comment]
@gordol It's in newer versions of Android.  `PERMISSION_WRITE_EXTERNAL_STORAGE ` used to be an implicit permission that didn't require asking the user at runtime.  Including it within the Manifest file was enough to grant permission.  However, now (I believe as of Android N) you have to explicitly request the permission at runtime.

I don't quite have a pull request for this issue.  I've been making a few changes to the plugin so that it also supports Bluetooth printing.  However, in doing so I've pulled in a lot of code from Brother's examples, and I've added support for iOS. I'd be a bit worried at how much different my changes have made the Plugin.

Though if you are interested in them, I could possibly submit a pull request for discussion.

**Comment by sllobera** [comment]
Ill be interested on iOS version as I don’t have the time to do it myself

Tnx

**Comment by gordol** [comment]
Indeed, this is a Cordova plugin, so IOS PR are much welcomed!

**Comment by arcadius** [comment]
@Ayiga : Any progress on the support for iOS? :+1:

**Comment by arcadius** [comment]
Just an Off topic question:

(Note that I am new to label printing ...)

1- Is a p-touch template required for printing using this cordova plugin?

2-  Would this https://play.google.com/store/apps/details?id=com.brother.printservice&hl=en_GB
help print directly to from an app without this cordova plugin?
I have tried but the Brother Print Service could not find my QL-710w 

Thank you very much.

**Comment by gordol** [comment]
@arcadius  We have an open PR for IOS support here: https://github.com/gordol/cordova-brother-label-printer/pull/10

I'm about to merge it to dev branch, but it needs a little more work for full IOS support. (no bluetooth yet)

It also has support for better printer model handling. Please give it a try after I merge to dev, and let me know if you have any issues?

**Comment by arcadius** [comment]
@gordol  and @Ayiga , this PR looks awesome.

For now, I am still working on delivering my app on Android first.

So, at the moment, I do not yet have the capability of testing this on iOS :-(
But I will give it a go as soon as I am done with Android and Windows.
:+1:
