### ISSUE TITLE
Is there a Better way to Label Printing?

### ISSUE THREAD

**Issue by arcadius** [gordol/cordova-brother-label-printer#8]
First, I would like to thank you all @gordol , @momzor @ayiga , @sllobera , @ltrtom  for your hard work.

This is rather a set of questions 

(Note that I am new to label printing ...)

1-  Would this https://play.google.com/store/apps/details?id=com.brother.printservice&hl=en_GB
help print directly from an app without this cordova plugin?
I have tried but the Brother Print Service could not find my QL-710w.

2- IMHO, there must be a better way to label printing... 
let's say I need to support in my app 10 brands of label printers... with the current approach, I will have to integrate and bundle with my app 10 SDKs and their respective native libraries ... :-(
There must be a better way ... 

Thank you very much @gordol , @momzor @ayiga , @sllobera , @ltrtom  and others for your work on this 

Arcadius

**Comment by gordol** [comment]
Hi @arcadius 

Glad you got some use from this plugin. It is most definitely rough around the edges... so thanks for your patience.

There are no universal printing solutions for Android at the moment, that I'm aware of. Every manufacturer has proprietary drivers and APIs.

That being said, what are the 10 manufacturers that you need to support? If someone can get me the label printers, I'm happy to try to get them all working with a single library! 

Google has been working on a "native" print solution for ages, but as far as I know, it's not come to fruition yet.

Anyway, I wanted to let you know that I have seen your message, and am considering it, but I don't yet have a solution for you.

If you can let me know the manufacturers, I can do a little research and will report my findings here.

Best of luck!

**Comment by arcadius** [comment]
Thank you very much @gordol  for your message.
Most appreciated. :+1: 
For now, I need support only for Brother label printers .... I'll focus on that for now.
Thank you very much for starting work on this.
I am currently working on a fork at 
https://github.com/MenelicSoftware/cordova-plugin-brother-label-printer
and I will be adding support for Windows and later iOS too.

Later on, we can discuss how we can merge things together so that we have a unique and generic enough plugin for these label printers.

Thank you very much @gordol :+1:

**Comment by gordol** [comment]
Hi @arcadius just to let you know, on the dev branch, we have base-line support for IOS in progress, and there's now basic bluetooth printing support as well as the ability to set the printer model from JS via setPrinter()

**Comment by arcadius** [comment]
Hello @gordol 
Thank you very much for letting know.
I think it would be best if we try merging so that we avoid duplicate of effort

# Common JavaSript interface
In my fork, 
https://github.com/MenelicSoftware/cordova-plugin-brother-label-printer/blob/master/www/printer.js
I have exposed only one single interface.:
```javascript
printLabel(base64ImageOrPdfToPrint, {"numberOfCopies":1, "orientation":"LANDSCAPE", "labelName":"W62RB", "modelName":"QL-820NBW", "port":"NET"})

```
This internally does the printer finding etc ....
So, in the mobile app, one can have a setting page and change the printer model or port on the fly and print straight away without restarting the mobile app (the native Android code in my fork is stateless).

Please, think a bit about having a single JavaScript entry point .... take your time ....
IMHO, Having the printer search hidden from the caller simplifies a bit the system.

We need to work together @gordol  :+1: 

Thank you very much for the great work :1st_place_medal:

**Comment by gordol** [comment]
i don't think a single JS interface is sufficient, firstly, because there may be more than one way to print, and users may want to use use one or another. secondly, we also support pushing PJL to the printer via USB, this can be used, for example, to configure the printer's network settings, etc... from cordova, over usb. see here: https://github.com/gordol/PJL-Generator

that being said, if you want to have a fire and forget print method that encapsulates the others, i see no reason why that couldn't be added, as long as it doesn't break support for the current manual workflows.

**Comment by arcadius** [comment]
Thanks @gordol  for mentioning PJL.

Yes, we could have one interface for sending printer configurations/commands and one for the actual printing operation.

> that being said, if you want to have a fire and forget print method that encapsulates the others

This is not a fire and forget as such.
When you try to print and let's say the printer is off or no paper or something, you will still get an error message .... So you know what whent wrong.

**Comment by gordol** [comment]
Okay, I still want to keep the separate methods, ideally.

If you want to send a PR for an additional method that encapsulates the others, to attempt the first printer that is found, that would be reasonable.

The feature you want should be done fully in JS/Cordova space, I think, to avoid the necessity to port native code to all of the platforms. You can throw in an additional method in www/printer.js. It can run findPrinters, setPrinter, and then printViaSDK. Maybe you can call it something like findSetAndPrint or something along those lines... or printToAny or something along those lines...
