### ISSUE TITLE
Plugin Usage

### ISSUE THREAD

**Issue by dev-fJ-del** [gordol/cordova-brother-label-printer#9]
First of all, thank you @gordol  for the hard work put into this project, we all appreciate it.
I'm quite new to this .git and plugin environment, and would like to know if it is possible to provide a usage instruction as in real-life scenario.

I've found the printer(RJ-4040), but calling the printViaSDK with base64 image, returns error code:ERROR_NOT_SAME_MODEL
Code:
```
   cordova.plugins.brotherPrinter.findNetworkPrinters(function (bool, printers) {
                alert(bool + '\n' + printers);
                if (bool == true) {
                    cordova.plugins.brotherPrinter.printViaSDK(img, function (error) {
                        alert(error);
                    });
                }
            });
```
I've ensured that my device and printers are on the same wifi with the same i.p range.
I suspect that the base64 is wrongly formatted.
If you can provide an example how you guys managed to print via js I would appreciate it.

Thanks again

**Comment by gordol** [comment]
Hi, can you try the new changes that are on the dev branch?

Now you can get a list of printers, and select the one you want. The readme needs to be updated, but take a peek at www/printer.js at the findNetworkPrinters and setPrinter methods.

**Comment by gordol** [comment]
if you're not able to print still, please re-open this issue :) good luck!

**Comment by dev-fJ-del** [comment]
Thank you again for the awesome work done!
Will give feedback

**Comment by dev-fJ-del** [comment]
When I build the application template for cordova its giving me the
following error:
[image: Inline image 1]

**Comment by gordol** [comment]
I can't see that error, can you send the text of the error? Or upload the image somewhere?

**Comment by dev-fJ-del** [comment]
Build for android is started
Uploading an application template...
Completed
Building status: pending (5 attempts)
*Building status: error (List<Bitmap> cannot be converted to
ArrayList<Bitmap>)*
Removing the application template...
Completed
*Error: Building status: error (List<Bitmap> cannot be converted to
ArrayList<Bitmap>)*

**Comment by gordol** [comment]
Seems to me that code is from Brother...

https://github.com/gordol/cordova-brother-label-printer/pull/11/files#diff-7ffdcc51506a24e861e75e002ed22eddR19

I have asked the author to take a look.

**Comment by gordol** [comment]
Try now, he made a change to use a normal List now.
